# Generated by Django 2.2 on 2019-08-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190822_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='hashed_password',
            field=models.TextField(null=True),
        ),
    ]
